name: test ci

on:
  push:
    branches:
      - master
      - actions

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install check gcc -y
    - name: gcc version check
      run: |
        gcc --version
    - name: make cecs
      run: make cecs
    - name: make check
      run: make check
