name: test ci

on:
  push:
    branches:
      - master
      - actions

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        git clone https://github.com/libcheck/check.git --branch 0.13.0
        autoreconf --install
        ./configure
        make
        make check
        sudo make install
        sudo ldconfig
    - name: gcc version check
      run: |
        gcc --version
    - name: make cecs
      run: make cecs
    - name: make check
      run: make check
