name: ci

on:
  push:
    branches:
      - master
      - develop
      - ci

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Github Actions requires a single row to be added to the build matrix.
        #https://help.github.com/en/articles/workflow-syntax-for-github-actions
        name: [
          ubuntu-latest-clang,
          ubuntu-latest-gcc,
          macOS-latest-clang
        ]

        include:
          - name: ubuntu-latest-clang
            os: ubuntu-latest
            compiler: clang
          - name: ubuntu-latest-gcc
            os: ubuntu-latest
            compiler: gcc
          - name: macOS-latest-clang
            os: macOS-latest
            compiler: clang

    steps:
      - uses: actions/checkout@v1
      - name: install dependencies (ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install ${{ matrix.compiler }} --yes
          sudo apt-get install libyaml-0-2 libyaml-dev libyaml-doc --yes
          git clone https://github.com/libcheck/check.git --branch 0.13.0
          cd check
          autoreconf --install
          ./configure
          make
          make check
          sudo make install
          sudo ldconfig
          cd ..
          rm  -rf check
      - uses: actions/checkout@v1
      - name: install dependencies (macOS)
        if: startsWith(matrix.os, 'macOS')
        run: |
          brew install autoconf automake libtool check pkg-config libyaml
      - name: compiler version check
        run: ${{ matrix.compiler }} --version
      - name: components
        run: make components CC=${{ matrix.compiler }}
      - name: cecs
        run: make CC=${{ matrix.compiler }}
      - name: package
        run: make artifact
      - uses: actions/upload-artifact@v1
        with:
          name: cecs
          path: cecs.zip
