name: C/C++ CI

on:
  push:
    branches:
      - master
      - actions

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install check
    - name: make
      run: make
    - name: make check
      run: make check
