name: pipeline

on:
  push:
    branches:
      - master
      - develop
      - win-cross-comp
  pull_request:
    branches:
      - master
      - develop
      - win-cross-comp

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET: ${{ secrets.AWS_S3_BUCKET }}

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Github Actions requires a single row to be added to the build matrix.
        #https://help.github.com/en/articles/workflow-syntax-for-github-actions
        name: [
          ubuntu,
          macOS
        ]

        include:
          - name: ubuntu
            os: ubuntu-latest
            compiler: gcc
          - name: macOS
            os: macOS-latest
            compiler: clang

    steps:
      - uses: actions/checkout@v1
      - uses: chrislennon/action-aws-cli@v1.1

      - name: install dependencies (ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install ${{ matrix.compiler }} --yes
          sudo apt-get install libyaml-0-2 libyaml-dev libyaml-doc --yes
          git clone https://github.com/libcheck/check.git --branch 0.13.0
          cd check
          autoreconf --install
          ./configure
          CC=${{ matrix.compiler }} make
          sudo make install
          sudo ldconfig
          cd ..
          rm  -rf check

      - name: install dependencies (macOS)
        if: startsWith(matrix.os, 'macOS')
        run: |
          brew install autoconf automake libtool check pkg-config libyaml

      - name: compiler version check
        run: ${{ matrix.compiler }} --version

      - name: components
        run: make components CC=${{ matrix.compiler }}

      - name: cecs
        run: make CC=${{ matrix.compiler }}

      - name: package (ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          mkdir cecs
          cp *.so cecs
          cp *.a cecs

      - name: package (macOS)
        if: startsWith(matrix.os, 'macOS')
        run: |
          mkdir cecs
          cp *.dylib cecs
          cp *.a cecs

      - name: upload artifact (s3)
        run: |
          zip -r cecs.zip cecs
          aws s3 cp cecs.zip s3://$BUCKET/${{ matrix.name }}/cecs-$GITHUB_SHA.zip

  xci:
    env:
      XCC: x86_64-w64-mingw32-gcc
      HCC: gcc
      HOST: x86_64-w64-mingw32
      PREFIX: /usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/
      LIBDIR: /usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/lib/
    name: mingw
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: chrislennon/action-aws-cli@v1.1

      - name: install dependencies (mingw)
        run: |
          sudo apt-get install gcc-mingw-w64 gcc-mingw-w64-x86-64 --yes
          sudo apt-get install mingw-w64 binutils-mingw-w64 mingw-w64-tools --yes
          sudo apt-get install libyaml-0-2 libyaml-dev libyaml-doc --yes
          sudo apt-get install wine-stable wine-binfmt
          sudo dpkg --add-architecture i386 && sudo apt-get install wine32
          sudo update-binfmts --import /usr/share/binfmts/wine

      - name: building libyaml (mingw)
        run: |
          git clone https://github.com/yaml/libyaml.git
          cd libyaml
          ./bootstrap
          ./configure --host=${{ env.HOST }} --prefix=${{ env.PREFIX }} --libdir=${{ env.LIBDIR }}
          CC=${{ env.XCC }} make
          sudo make install
          sudo ldconfig ${{ env.LIBDIR }}
          cd ..
          rm -rf libyaml

      - name: building libcheck (mingw)
        run: |
          git clone https://github.com/libcheck/check.git --branch 0.13.0
          cd check
          autoreconf --install
          ./configure --host=${{ env.HOST }} --prefix=${{ env.PREFIX }} --libdir=${{ env.LIBDIR }}
          CC=${{ env.XCC }} make
          sudo make install
          sudo ldconfig ${{ env.LIBDIR }}
          cd ..
          rm  -rf check

      - name: building libcheck (native)
        run: |
          git clone https://github.com/libcheck/check.git --branch 0.13.0
          cd check
          autoreconf --install
          ./configure
          CC=${{ env.HCC }} make
          sudo make install
          sudo ldconfig
          cd ..
          rm  -rf check

      - name: lib output
        run: |
          echo "========== PREFIX DIR =========="
          ls ${{ env.PREFIX }}
          echo "========== PREFIX DIR/LIB =========="
          ls ${{ env.LIBDIR }}
          echo "========== PREFIX DIR/INCLUDE =========="
          ls ${{ env.PREFIX }}include
          pkg-config --cflags check
          pkg-config --libs check

      - name: compiler version check
        run: ${{ env.XCC }} --version

      - name: components
        run: make components CC=${{ env.XCC }}

      - name: cecs
        run: make CC=${{ env.XCC }}

      - name: package (mingw)
        run: |
          mkdir cecs
          cp *.dll cecs
          cp *.lib cecs

      - name: upload artifact (s3)
        run: |
          zip -r cecs.zip cecs
          aws s3 cp cecs.zip s3://$BUCKET/mingw/cecs-$GITHUB_SHA.zip


  is-release-ready:
    needs: [ci, xci]
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: get version variables
        run: |
          echo "::set-env name=VMAJOR::$(cut -d . -f1 .version)"
          echo "::set-env name=VMINOR::$(cut -d . -f2 .version)"
          echo "::set-env name=VPATCH::$(cut -d . -f3 .version)"
          echo "::set-env name=VERSION::v$(cat .version)"

      - name: ensure version has been updated
        run: |
          PREVVER=$(git tag | tail -1)
          if [ $PREVVER == $VERSION ]; then
            echo "version not incremented! Aborting release"
            exit 1
          fi
        shell: bash

  release:
    needs: is-release-ready
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: chrislennon/action-aws-cli@v1.1

      - name: get version variables
        run: |
          echo "::set-env name=VMAJOR::$(cut -d . -f1 .version)"
          echo "::set-env name=VMINOR::$(cut -d . -f2 .version)"
          echo "::set-env name=VPATCH::$(cut -d . -f3 .version)"
          echo "::set-env name=VERSION::v$(cat .version)"

      - name: create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}${{ env.RSUFFIX }}
          draft: false
  
      - name: get artifacts
        run: |
          aws s3 cp s3://$BUCKET/ubuntu/cecs-$GITHUB_SHA.zip\
           cecs-linux-$VERSION
          aws s3 cp s3://$BUCKET/macOS/cecs-$GITHUB_SHA.zip\
           cecs-darwin-$VERSION
          aws s3 cp s3://$BUCKET/mingw/cecs-$GITHUB_SHA.zip\
           cecs-windows-$VERSION

      - name: upload release artifacts (linux)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./cecs-linux-${{ env.VERSION }}
          asset_name: cecs-linux-${{ env.VERSION }}
          asset_content_type: application/zip

      - name: upload release artifacts (macos)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./cecs-darwin-${{ env.VERSION }}
          asset_name: cecs-darwin-${{ env.VERSION }}
          asset_content_type: application/zip

      - name: upload release artifacts (windows)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./cecs-windows-${{ env.VERSION }}
          asset_name: cecs-windows-${{ env.VERSION }}
          asset_content_type: application/zip
